<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="DannyGoodacre.Primitives">
        <HintPath>..\..\..\.nuget\packages\dannygoodacre.primitives\0.11.1\lib\net10.0\DannyGoodacre.Primitives.dll</HintPath>
      </Reference>
      <Reference Include="Orleans.Core.Abstractions">
        <HintPath>..\..\..\.nuget\packages\microsoft.orleans.core.abstractions\10.2.2\lib\net10.0\Orleans.Core.Abstractions.dll</HintPath>
      </Reference>
      <Reference Include="Orleans.Runtime">
        <HintPath>..\..\..\.nuget\packages\microsoft.orleans.runtime\10.2.2\lib\net10.0\Orleans.Runtime.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Blackjack.Application\Blackjack.Application.csproj" />
      <ProjectReference Include="..\Blackjack.Domain\Blackjack.Domain.csproj" />
      <ProjectReference Include="..\Blackjack.Events\Blackjack.Events.csproj" />
      <ProjectReference Include="..\Blackjack.Requests\Blackjack.Requests.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Orleans.CodeGenerator" Version="10.3.1">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.Orleans.Sdk" Version="10.3.1" />
      <PackageReference Include="Microsoft.Orleans.Serialization.SystemTextJson" Version="10.3.1" />
    </ItemGroup>

</Project>
